apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: invapp
  name: invapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: invapp
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: invapp
    spec:
      containers:
      - image: eswaribala/ericecommrepo:invappv1
        name: v1
        resources: {}
        env:
            - name: MYSQL_URL
              value: jdbc:mysql://mysql:3306/ericnov2021batch1_prodinvdb?useSSL=false
               

status: {}
--- 
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: invservice
  name: invservice
spec:
  ports:
  - name: 7076-7070
    port: 7070
    protocol: TCP
    targetPort: 7076
  selector:
    app: invapp
  type: ClusterIP
status:
  loadBalancer: {}
